### PR TITLE
Add the ability to specify a vendor directory

### PR DESCRIPTION
**Pull request by davecheney**
Fixes issue 29

You probably won't agree with my choice of config key.

### CODE REVIEW

**Comment by skelterjohn** [comment]
I'm not sure I like this method in general. It seems complicated, and complicates an already complicated (internal) interface.

There are two approaches to getting this done.

1) Allow gb.cfg to tell gb to ignore a path element when figuring out the target. This is straightforward to do, and would involve trimming the variable "base" in ScanDirectory().

2) Allow gb.cfg to add elements to $GOPATH for the current target, and possibly targets in all subdirectories. I think this is in essence what your pull request does, though it doesn't seem to observe $GOPATH conventions (which are, frankly, some silly conventions that I try to follow just to stay compatible).

However I think it has a flaw in that it can't leapfrog a subdirectory, with no target (so pkg is nil), that has its own subdirectory containing a valid target. This is easily remedied.

If I take approach 2 (which I like better), I want it to not allow projects that can't be built easily (more or less) by the go tool. That is, something like

> GOPATH+=vendor go build mystuff

Maybe a line in gb.cfg could look like:
gopath+=vendor1
gopath+=vendor2
in the same file. I don't want something like "vendor1:vendor2" because on windows it'd have look like "vendor1;vendor2".

And then pass the extra GOPATH entries down ScanDirectory() recursively. I also think I want to collect the data that's being passed down in a struct, just to simplify the code a bit.

**Comment by skelterjohn** [comment]
Just in case - what I'm suggesting is based on what you suggested and differs mostly in some arbitrary conventions and some code since I want to do a bit of refactoring anyway. Don't think I'm pretending this was my own idea :)

**Comment by skelterjohn** [comment]
Been thinking about it more, and allowing gb.cfg to set GOPATH for subdirectories is problematic because the normal behavior of gb is such that the -R option has gb go into GOROOT and GOPATH to build extra targets.

Making it so that 
1) only a subset of all packages (those that have a parent with the right gb.cfg) have access to this GOPATH, and
2) -R can rebuild targets in this GOPATH
at the same time would be very difficult. One or the other is easy - (2) can be done by just adding to the var GOPATH []string at the right time. (1) can be done by just telling the compiler about the path for the particular projects.

Doing (1) and (2) would require a lot of work, and potentially a big rewrite.

So, it seems like just being able to specify a custom import location would be the most straightforward. But there is another problem here - in your case, the extra argument for 6g would be "-I ../whatever/vendor/_obj/$GOOS_$GOARCH" (assuming gb was used to build vendor; if "go build" was used, replace _obj with pkg).

That is, something you don't necessarily know when you write gb.cfg. I _could_ have it automatically check for <thePathYouGave>/_obj/$GOOS_GOARCH and <thePathYouGave>/pkg/$GOOS_GOARCH, as well as <thePathYouGave>, but this is starting to get complicated.

Thoughts?

**Comment by davecheney** [comment]
> I'm not sure I like this method in general. It seems complicated, and complicates an already complicated (internal) interface.

Agreed, the idea of one Target requiring the Cfg of another to
determine it's name was not natural, and required grafting on that
ability (although the graft isn't too ugly)

> However I think it has a flaw in that it can't leapfrog a subdirectory, with no target (so pkg is nil), that has its own subdirectory containing a valid target. This is easily remedied.

I never found a situation when a NewPackage returned a nil Package, it
does return an error, but pkg is always valid.

> If I take approach 2 (which I like better), I want it to not allow projects that can't be built easily (more or less) by the go tool. That is, something like
> 
> > GOPATH+=vendor go build mystuff
> 
> Maybe a line in gb.cfg could look like:
> gopath+=vendor1
> gopath+=vendor2
> in the same file. I don't want something like "vendor1:vendor2" because on windows it'd have look like "vendor1;vendor2".

That sounds like a good solution.

**Comment by davecheney** [comment]
> Been thinking about it more, and allowing gb.cfg to set GOPATH for subdirectories is problematic because the normal behavior of gb is such that the -R option has gb go into GOROOT and GOPATH to build extra targets.

Ahh, because GOROOT and GOPATH are special cases handled after the
initial ScanDirectory of the Workspace.

> Making it so that
> 1) only a subset of all packages (those that have a parent with the right gb.cfg) have access to this GOPATH, and
> 2) -R can rebuild targets in this GOPATH
> at the same time would be very difficult. One or the other is easy - (2) can be done by just adding to the var GOPATH []string at the right time. (1) can be done by just telling the compiler about the path for the particular projects.
> 
> Doing (1) and (2) would require a lot of work, and potentially a big rewrite.

I don't really understand enough about the GOPATH stuff to comment.
What I do understand is GOPATH is passed to 6l when linking, but what
I need is a way to adjust the inferred path name of a package when
being compiled by 6g, that inference would drop certain path prefixes.

> So, it seems like just being able to specify a custom import location would be the most straightforward. But there is another problem here - in your case, the extra argument for 6g would be "-I ../whatever/vendor/_obj/$GOOS_$GOARCH" (assuming gb was used to build vendor; if "go build" was used, replace _obj with pkg).
> 
> That is, something you don't necessarily know when you write gb.cfg. I _could_ have it automatically check for <thePathYouGave>/_obj/$GOOS_GOARCH and <thePathYouGave>/pkg/$GOOS_GOARCH, as well as <thePathYouGave>, but this is starting to get complicated.

Yes, that starts to get complicated. The initial idea you gave,
extending the facility to trim package targets that started with src
or pkg worked quite well as the rest of the gb harness just worked.
But making the name of the item to trim configurable introduced a lot
of complexity.

**Comment by skelterjohn** [comment]
> Yes, that starts to get complicated. The initial idea you gave,
> extending the facility to trim package targets that started with src
> or pkg worked quite well as the rest of the gb harness just worked.
> But making the name of the item to trim configurable introduced a lot
> of complexity.

It could be as simple as having a gb.cfg with the contents "nobase=true".

Just occurred to me, if you put "target=." into vendor/gb.cfg, it seems like that should tell gb to start below vendor, and then get "./launchpad.net/mgo", which would be cleaned to "launchpad.net/mgo". However this is not the case - going to investigate why.

**Comment by davecheney** [comment]
> Just occurred to me, if you put "target=." into vendor/gb.cfg, it seems like that should tell gb to start below vendor, and then get "./launchpad.net/mgo", which would be cleaned to "launchpad.net/mgo". However this is not the case - going to investigate why.

That was the first thing I tried, essentially resetting the target
computation at that level. If you could make that work, that would be
the best solution I thnk.

**Comment by skelterjohn** [comment]
Setting the target in the empty directory works, now. It was definitely a bug.

**Comment by davecheney** [comment]
Brilliant.

**Pull request closed without merging**
